### ISSUE TITLE
[Barreleye/Palmetto - build v1.0-89-g5bc571e-dirty ] Unexpected build version suffix

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc-build-scripts#10]
Reference : https://github.com/openbmc/openbmc-test-automation/issues/43

The version has -dirty in the build version..  

Example  '"v1.0-89-g5bc571e-dirty"'

**Comment by geissonator** [comment]
We see a similar thing when building the official releases internally as well.

**Comment by gkeishin** [comment]
is this going to get fix ? we still see now as well

**Comment by gkeishin** [comment]
This is no longer seen in newer builds.. expecting this is fixed.. closing the issue

**Comment by mdmillerii** [comment]
Probably fixed by openbmc/openbmc@98e61e4542a2cdc9e9dd32a20e6e5186a87d82a5 which was tagged 
Fixes openbmc/openbmc#820.
