### ISSUE TITLE
run-qemu-robot-test.sh no longer passes

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc-build-scripts#13]
Not sure if the strings changed or what, but the expect script is not successfully logging into the QEMU image anymore so the run is not proceeding:

```
09:23:12 Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) 0.1.0 qemuarm ttyAMA0

09:23:12 

09:23:12 qemuarm login: root

09:23:12 + grep -q OPENBMC-READY
09:23:12 + sleep 2
09:23:14 + '[' 0 -gt 0 ']'
09:23:14 + '[' 0 -eq 0 ']'
09:23:14 + echo 'Timed out waiting for QEMU, exiting'
```

**Comment by fangkaiyu2023** [comment]
+ obmc_qemu_docker=329a1b3d073f011e9b79ecbe57b16647245777b84eb08e12a6ab7aa564eb089c
+ DOCKER_SSH_PORT=22
+ DOCKER_HTTPS_PORT=443
+ trap '' PIPE
++ docker inspect 329a1b3d073f011e9b79ecbe57b16647245777b84eb08e12a6ab7aa564eb089c
++ grep 'IPAddress":'
++ tail -n1
++ cut -d '"' -f 4
+ DOCKER_QEMU_IP_ADDR=172.17.0.2
+ delay=5
+ attempt=120
+ '[' 120 -gt 0 ']'
+ attempt=119
+ echo 'Waiting for qemu to get to standby (attempt: 119)...'
Waiting for qemu to get to standby (attempt: 119)...
++ docker logs 329a1b3d073f011e9b79ecbe57b16647245777b84eb08e12a6ab7aa564eb089c
+ result='spawn /tmp/openbmc/build/boot-qemu.sh


+ set -uo pipefail

+ QEMU_ARCH=x86_64-linux

+ echo '\''QEMU_ARCH = x86_64-linux'\''

QEMU_ARCH = x86_64-linux

+ [[ -z x86_64-linux ]]

+ BASE_DIR=/tmp/openbmc/build

+ echo '\''BASE_DIR = /tmp/openbmc/build'\''

BASE_DIR = /tmp/openbmc/build

+ [[ ! -d /tmp/openbmc/build ]]

+ QEMU_BIN=./qemu-system-arm

+ DEFAULT_MACHINE=versatilepb

+ MACHINE=romulus

+ cd /tmp/openbmc/build

+ DEFAULT_IMAGE_LOC=./images

+ '\''['\'' -f ./images/romulus/obmc-phosphor-image-romulus.ubi.mtd '\'']'\''

+ '\''['\'' -f ./images/romulus/obmc-phosphor-image-romulus.static.mtd '\'']'\''

+ DRIVE=obmc-phosphor-image-romulus.static.mtd

++ mktemp /tmp/obmc-phosphor-image-romulus.static.mtd-XXXXX

+ TMP_DRIVE_PATH=/tmp/obmc-phosphor-image-romulus.static.mtd-JyqQb

+ '\''['\'' romulus = versatilepb '\'']'\''

+ cp ./images/romulus/obmc-phosphor-image-romulus.static.mtd /tmp/obmc-phosphor-image-romulus.static.mtd-JyqQb

'
+ grep -q OPENBMC-READY
+ sleep 5
+ '[' 119 -gt 0 ']'
+ attempt=118
+ echo 'Waiting for qemu to get to standby (attempt: 118)...'
Waiting for qemu to get to standby (attempt: 118)...
++ docker logs 329a1b3d073f011e9b79ecbe57b16647245777b84eb08e12a6ab7aa564eb089c
Error response from daemon: No such container: 329a1b3d073f011e9b79ecbe57b16647245777b84eb08e12a6ab7aa564eb089c
+ result=
Build step 'Execute shell' marked build as failure
Finished: FAILURE
