### ISSUE TITLE
Does not collect the tar images

### ISSUE THREAD

**Issue by mkumatag** [openbmc/openbmc-build-scripts#2]
part of https://github.com/openbmc/openbmc/commit/b7bc04b9820b11b50593ad2e672c990965fae89a changeset, there has been code delivered to tar the image for the bitbake build but jenkins is not able to collect the tar images.

**Comment by shenki** [comment]
I think we need to correct the bitbake script to place the images in the correct output location?

**Comment by mkumatag** [comment]
but by default when I do a bitbake on my ubuntu machine I could able see tar files in tmp/deploy/images/palmetto/ folder. this is what the complete list of files looks like:

ubuntu@jupiter-vm894:~/mak/openbmc/build$ ls tmp/deploy/images/palmetto/
core-image-minimal-initramfs-palmetto-20160210171530.rootfs.cpio.lzma       image-bmc                                                       obmc-phosphor-image-palmetto.cpio.gz
core-image-minimal-initramfs-palmetto-20160210171530.rootfs.manifest        image-initramfs                                                 obmc-phosphor-image-palmetto.ext4
core-image-minimal-initramfs-palmetto.cpio.lzma                             image-kernel                                                    obmc-phosphor-image-palmetto.manifest
core-image-minimal-initramfs-palmetto.cpio.lzma.u-boot                      image-rofs                                                      obmc-phosphor-image-palmetto.squashfs-xz
core-image-minimal-initramfs-palmetto.manifest                              image-rwfs                                                      palmetto-20160210171530.all.tar
cuImage                                                                     image-u-boot                                                    palmetto-20160210171530.tar
cuImage--4.3+git0+fe68a785af-r0-aspeed-bmc-opp-palmetto-20160210171530.dtb  modules--4.3+git0+fe68a785af-r0-palmetto-20160210171530.tgz     README_-_DO_NOT_DELETE_FILES_IN_THIS_DIRECTORY.txt
cuImage--4.3+git0+fe68a785af-r0-palmetto-20160210171530.bin                 modules-palmetto.tgz                                            rwfs.ext4
cuImage-aspeed-bmc-opp-palmetto.dtb                                         obmc-phosphor-image-palmetto-20160210171530.rootfs.cpio.gz      u-boot.bin
cuImage-palmetto.bin                                                        obmc-phosphor-image-palmetto-20160210171530.rootfs.ext4         u-boot-palmetto.bin
flash-palmetto                                                              obmc-phosphor-image-palmetto-20160210171530.rootfs.manifest     u-boot-palmetto-v2013.07+gitAUTOINC+e00b3cc675-r0.bin
flash-palmetto-20160210171530                                               obmc-phosphor-image-palmetto-20160210171530.rootfs.squashfs-xz
ubuntu@jupiter-vm894:~/mak/openbmc/build$
