### ISSUE TITLE
Error parsing reference: "ubuntu:bionic as openbmc-base" is not a valid repository/tag

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc-build-scripts#21]
We're getting this on our x86 based CI machines. It works ok on our POWER based CI system so no idea what's going on yet:

https://openpower.xyz/job/openbmc-repository-ci/

```
12:26:47 + docker build --network=host -t openbmc/ubuntu-unit-test -
12:26:47 Sending build context to Docker daemon 9.728 kB

12:26:47 Step 1/67 : FROM ubuntu:bionic as openbmc-base
12:26:47 Error parsing reference: "ubuntu:bionic as openbmc-base" is not a valid repository/tag: invalid reference format
12:26:47 ++ cleanup
12:26:47 ++ local status=1
12:26:47 ++ '[' -n /tmp/tmp.3hfpsTLe0x ']'
12:26:47 ++ rm -f /tmp/tmp.3hfpsTLe0x
12:26:47 ++ trap - EXIT ERR
12:26:47 ++ exit 1
```

**Comment by geissonator** [comment]
For now I've just changed the jenkins CI job to only use the POWER system. This seems like maybe a docker version thing?

POWER:
```
docker --version
Docker version 17.06.0-ce, build 411dd6e
```

x86:
```
docker --version
Docker version 1.13.1, build 092cba3
```

That seems ridiculously old... I'll see if I can update it.

**Comment by wak-google** [comment]
Yeah, I believe the AS part of the FROM line was added in a 2017 version. 2017.06 must have it because the tests pass sometimes.

**Comment by geissonator** [comment]
Darn, got the x86 systems updated but ending up with this version which does not work:
```
 docker --version
Docker version 17.03.2-ce, build f5ec1e2
```
Will need to look into manually updating my ubuntu links to get more recent.

**Comment by wak-google** [comment]
Is this coming from the upstream docker repos?

**Comment by matthewfischer** [comment]
I believe this is closable.
