### ISSUE TITLE
build-qemu-rebot-docker.sh needs to add somethings

### ISSUE THREAD

**Issue by fangkaiyu2023** [openbmc/openbmc-build-scripts#34]
libsdl2-dev \
    libsdl2-2.0-0 \
    numactl

**Comment by williamspatrick** [comment]
Patches welcome on Gerrit?

it would be helpful if you could give some rationale.

**Comment by fangkaiyu2023** [comment]
I described the specific information of the problem in detail under this
issue, I hope I expressed it clearly enough.
https://github.com/openbmc/openbmc-build-scripts/issues/34

Patrick Williams ***@***.***> 于2023年5月23日周二 17:52写道：
