### ISSUE TITLE
Segmentation fault in meson test

### ISSUE THREAD

**Issue by psulewsx** [openbmc/openbmc-build-scripts#39]
When executing `meson test` in the docker, all tests fail with a segmentation error. This situation does not occur outside the docker. 
Meson setup is run as follows
 `meson setup build -Dtests=enabled -Db_coverage=true --optimization=0`

I'm running my docker according to this [instruction](https://github.com/openbmc/docs/blob/master/testing/local-ci-build.md)

**Comment by williamspatrick** [comment]
Against which repo?

Usually that is in the Valgrind or ASAN/UBSAN phases indicating a failure of some sort. Do you have the full log you can upload to gist?

**Comment by amboar** [comment]
Can you provide a bit more information about your environment and what repo your trying to run the tests for? Maybe some output from `meson setup` would be helpful also?

**Comment by psulewsx** [comment]
I used the interactive docker mode and after adding support for valgrind in boost, you have to add the appropriate flag in meson setup. The problem was solved
